### ISSUE TITLE
Label for Variable Name

### ISSUE THREAD

**Issue by ghowoo** [kaz-yos/tableone#21]
Is it possible to show labels instead of variable names in the output? For example, show "Age in Years (median [IQR]) " instead of show "age_in_years (median [IQR]) ". Thanks.

**Comment by kaz-yos** [comment]
Not at this moment. One thing you can do is to rename variables to what you want, which can contain spaces.

**Comment by ghowoo** [comment]
This is a very useful package. Hopefully it will work in future.

**Comment by tormodb** [comment]
Is this supposed to be supported now? There is an argument `varLabels` in the print function, but it does not print the labels although they do contain a label as documented by `labelled::var_label()`

Example:

`labelled::var_label(inoc$sebdtot)`
`[1] "SDQ total problems"`

in table:

`print(test$ContTable, smd = T, missing = T, explain = T, varLabels = T, printToggle = T, test = T)`

`sebdtot (mean (sd))` ....

**Comment by kaz-yos** [comment]
Can you try the following? Variable label is implemented for ```print.TableOne```, but not for ```print.ContTable```.
```
print(test, smd = T, missing = T, explain = T, varLabels = T, printToggle = T, test = T)
```

**Comment by tormodb** [comment]
Oh great, yes that does work.

But there is something strange going on, and I need to use the $ConTable as print.TableOne for some reason treat my continous variables as categorical. This is probably a different issue.



På 23. februar 2018 kl. 22:15:57, Kazuki Yoshida (notifications@github.com<mailto:notifications@github.com>) skrev:

Can you try the following? Variable label is implemented for print.TableOne, but not for print.ContTable.

print(test, smd = T, missing = T, explain = T, varLabels = T, printToggle = T, test = T)

**Comment by kaz-yos** [comment]
The "continuous" variable you are using is probably an ordinal variable with discrete levels and these levels probably have level labels.

**Comment by tormodb** [comment]
So, in regards to the other problem:

str(str(inoc$sebdtot)
Classes 'labelled', 'numeric'  atomic [1:9079] 13 11 4 9 3 9 19 13 9 12 ...
  ..- attr(*, "label")= chr "SDQ total problems"

when passing this to the CreateTableOne function, it is treated as a factor variable (listing each response option [from 0-40] on separate lines, and giving med the frequency and n instead of the mean and SD.

That is why I had to use the $ConTable option for printing.

Do you know what might be going on?



På 23. februar 2018 kl. 22:15:57, Kazuki Yoshida (notifications@github.com<mailto:notifications@github.com>) skrev:

Can you try the following? Variable label is implemented for print.TableOne, but not for print.ContTable.

print(test, smd = T, missing = T, explain = T, varLabels = T, printToggle = T, test = T)

**Comment by kaz-yos** [comment]
Please try dropping the ```val_labels``` from the offending variable. https://cran.r-project.org/web/packages/labelled/vignettes/intro_labelled.html

**Comment by tormodb** [comment]
Thanks for being so responsive. Unfortunately, that didn't change anything and the variable is still treated as factor/ordinal.

```
labelled::var_label(inoc$sebdtot) <- NULL
labelled::var_label(inoc$sebdtot)
NULL
```

`print(test3, smd = T, varLabels = T, showAllLevels = F)`

(Actual values removed)

```
                                Stratified by equal
                                 Accurate      Overestimate  Underestimate p      test SMD   
  n                               2228          2061          1687                           
  sebdtot (%)                                                                       
     0                                                 
     1                                
     2
     ....
    40  
```

**Comment by kaz-yos** [comment]
vaL_label

**Comment by tormodb** [comment]
Sorry for the misunderstanding. 

None of the variables have any val_labels:

```
> labelled::val_labels(inoc$sebdtot)
NULL
```

Also, I am able to successfully feed these variables to different package generating functions (i.e., `Hmisc:summaryM, tangram, CompareGroups, aresenal::tableBy` without any problems with the variables. 

I would prefer to use your package though, as it has some advantages when using it for my purposes (such as `knitr::kable` printing and the automatic function for SMDs).

**Comment by kaz-yos** [comment]
For some reason your variable has Classes 'labelled', 'numeric'. labelled is a class for a variable with val_label. CreateTableOne assumes such variables as categorical automatically. If you are not using cal_label, you can as.numeric() the variable in question to drop the labelled class.

**Comment by Poelemeijer** [comment]
Dear @kaz-yos,

I think I'm running into the same problem as @tormodb did, but I can't find a way to fix the issue. The problem is as follow:

To clean the data I use the following R-script:
`df$xvariable <- dplyr::recode(df$variable `0` = 0L, `1` = 1L, .default = 0L, .missing = 0L )`

This creates an integer-class variable. If I want to set a variable label and value labels, I use the codes provided by the labelled-package (as recommended in the TableOne help files).

`var_label(df$xvariable) <- "Variable name"
val_labels(df$xvariable) <- c(No = 0, Yes = 1)`

The output generates the name `Variable name` as expected when `var_label(df$xvariable)` is called into the console. The class is changed to `labelled` and now if I want to create use `CreateTableOne` the labels are not shown when using `data = subset(df, ...)`.

Is there any reason why the subset function breaks the label-output?

**Comment by kaz-yos** [comment]
```subset``` is pre-tidyverse so it may break variable labels. Please construct a temporary dataset using subset and examine if the subset dataset retains variable labels.

**Comment by tormodb** [comment]
I can confirm that subset removes labels, dplyr::filter preserves them, so may be a better approach.

My other problem was solved using the helpful suggestions above.
