### ISSUE TITLE
output with R markdown 

### ISSUE THREAD

**Issue by SophiaJia** [kaz-yos/tableone#24]
Hi,

thank you very much such a great package, it is very handy, 
I am trying to output the result from createTableOne to doc file, but neither r markdown not html works, and Copy/Paste from the console will mixed up the format. How do you output the table to other document?

**Comment by kaz-yos** [comment]
These days I typically write to an Excel file, clean it there, and copy to a Word file. Shown below is an example.

https://cran.r-project.org/web/packages/tableone/vignettes/introduction.html
```{R}
tab3Mat <- print(tab3, nonnormal = biomarkers, exact = "stage", quote = FALSE, noSpaces = TRUE, printToggle = FALSE)
## Save to a CSV file
write.csv(tab3Mat, file = "myTable.csv")
```

**Comment by William3342** [comment]
It would be really nice if the output were knitr compatible as I sometimes knit HTML documents to show my work.

**Comment by higgi13425** [comment]
Would it make sense to pass the object to David Gohel's flextable package? This allows you to put a table into Rmarkdown, and then with pandoc >2.0, to make both MS Word and MS PPT output.

**Comment by mikedolanfliss** [comment]
^I'm very interested in this work flow. Haven't quite been sure the best way to get from table one to markdown. Maybe a less formatted, but still tableone-ified version of the object could be accessible with a function or object slot to pass directly to any of the table formatting packages...

**Comment by kaz-yos** [comment]
Is the text matrix ```tab3Mat``` above too formatted for that purpose? I wonder which table-formatter package is the standard these days.

**Comment by mikedolanfliss** [comment]
I think so Kaz, yes, though you do bring up a good point about the multitude of potential table packages. I think being able to access the table one data as a data frame in some form, with factors, numerics and all, would be most helpful so that other packages can apply their own numeric formatting there. I suppose the current workflow means getting the text matrix and carefully casting it back to the implied data types (means/medians are numeric, etc.) and sending it to another formatter.

**Comment by chrisleboa** [comment]
I still think this is an issue @kaz-yos . I am trying to use the kableone function so that my tableone object prints but it will not work once these additional non-normal parameters are added.
