### ISSUE TITLE
using tableone within jamovi module

### ISSUE THREAD

**Issue by sbalci** [kaz-yos/tableone#58]
Dear @kaz-yos 

Previously I tried to contact with email.
I have built a https://github.com/jamovi/jamovi module to ease my friends research. For the descriptive statistics part, I have used some `tableone` functions as well. 

Since the module has many dependencies its size is big that is why it is not currently included in the jamovi library. It can be installed install using side-load.

I would like to thank for your package. I hope it will be more commonly used by non-R users as well.  

Best wishes

Details: https://sbalci.github.io/ClinicoPathJamoviModule/
windows: https://library.jamovi.org/win64/R3.6.1/ClinicoPath-0.0.1.jmo
macOS: https://library.jamovi.org/macos/R3.6.1/ClinicoPath-0.0.1.jmo
https://sbalci.github.io/ClinicoPathJamoviModule/reference/figures/jamovi-sideload.gif

**Comment by ndevln** [comment]
Just out of curiosity. What would be your filesize goal?

There are 2 large dependencies:
* lmerTest at ~53 Mb
* labelled  at ~23 Mb

MASS, survey and nlme are part of R-recommend. Maybe you have them already installed.

* e1071 is 1Mb
* gmodels is less than 3 Mb
* zoo is 1Mb.

R allows you to set the dependencies which should be installed yourself. So, you could just drop `lmerTest `if you don't use the 
`ShowRegTable()` with `lme4` function. `labelled` is needed.

@kaz-yos could `lmerTest` be made optional since `lme4` is also optional? Also, as far as I read it, a Model has to be created with lmerTest to invoke the Code path for lmerTest?

PS: Package sizes were calculated with https://github.com/r-lib/itdepends and some packages could share dependencies. But according to itdepends `tableone` is 84 Mb.

**Comment by sbalci** [comment]
Dear @ndevln and @kaz-yos ,

Thank you for the information.
We have resolved the size issue by making submodules. And `tableone` is available for use within [jamovi](https://www.jamovi.org) via ClinicoPath module now.

Best wishes
