### ISSUE TITLE
Hmisc labels cause continuous vars to be treated as factors

### ISSUE THREAD

**Issue by proshano** [kaz-yos/tableone#64]
Hello and thank you for creating this great package.

I noticed that continuous variables to which labels are applied are treated as factors in TableOne.

as.numeric fixes the problem but then it strips the labels.

I see that the handling of categorical variables allows for variable labels but continuous variables do not.

Thank you again for your great work.

**Comment by ndevln** [comment]
Hi,

As you read in #57 this was already my suspicion. If you could provide a minimal example, it would really speed up fixing the problem.

But at least I now have a vague idea which labels are causing the problem.

Greetings
Alex

**Comment by kaz-yos** [comment]
@proshano and @ndevln, thanks for figuring this out. I do not use `Hmisc` for labelling and use `labelled` instead so it went unnoticed. I wonder which labelling packages are currently common. Whatever fix we will do should not break the behavior of other commonly used labelling packages.

**Comment by ndevln** [comment]
Hi @kaz-yos,

as far as I know there are 4 types of labelling `labelled`, `haven`, `sjlabelled` and `Hmisc`. The first 3 seem to be working. Only `Hmisc` use the class `labelled` also for continuous (i.e. numeric) variables. Since this is checked here: https://github.com/kaz-yos/tableone/blob/3deaf81550010f09028251fc07783b6685c20c89/R/CreateTableOne.R#L158

these variables are treated as factors. 

And it seems that there was change in `labelled` and `haven`, which now use the class "haven_labelled" (both since Package version 2.0?). Both packages don't support value labels for factor variables and now recommend using factor labels directly (maybe this is a recent change). Just dropping the `labelled` class from the check above should fix everything, I think?!?

I will try it out.

Greetings,
Alex

**Comment by kaz-yos** [comment]
Hi @ndevln,

Thank you so much for your contribution! The corresponding version is on its way to CRAN!
